Alwayse prepend or move to front

diff --git a/bin/python b/bin/python
--- a/bin/python
+++ b/bin/python
@@ -1,19 +1,29 @@
 #!/usr/bin/env bash
 
-export PATH="${PATH/"$MY_OPT_DIR/bin:"}"
+export PATH="${PATH#"$MY_OPT_DIR/bin:"}"
+export PATH="${PATH/":$MY_OPT_DIR/bin:"/":"}"
+export PATH="${PATH%":$MY_OPT_DIR/bin"}"
 PYTHON=${0##*/}
 
-if [ "$(which $0)" == "$(which $PYTHON)" ]; then
+if [ "$PATH" = "$MY_OPT_DIR/bin" ]; then
+	echo "Error: PATH would be empty after removing '$MY_OPT_DIR/bin'"
+	echo "PATH='$PATH'"
+	exit 1
+fi
+
+if [ "$(which $0)" = "$(which $PYTHON)" ]; then
 	echo "Error: Infinite loop detected ($PYTHON still points to $0)"
+	echo "Are there links to '$MY_OPT_DIR/bin' still in PATH?"
+	echo "PATH='$PATH'"
 	exit 1
 fi
 
 python_var_name () {
-	${1:-python} -V 2>&1 | sed 's/^Python \([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*$/PYTHON\1\2_PATH/'
+	${1:-python} -V 2>&1 | sed 's/^Python \([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*$/MY_PYTHON\1\2_PATH/'
 }
 
-PYTHONPATH_VAR=$(python_var_name "$PYTHON")
+PYTHONPATH_VAR="$(python_var_name "$PYTHON")"
 export PYTHONPATH="${!PYTHONPATH_VAR}"
-unset $PYTHONPATH_VAR
+unset "${!MY_PYTHON*}"
 
 "$PYTHON" "$@"
